version: 2.1

description: |
    Demo site deploy using the ryanshoover/wpengine CircleCI orb.

orbs:
    wpengine: ryanshoover/wpengine@0.2

workflows:
    version: 2

    build_test_deploy:
        jobs:
            - wpengine/lint
            - wpengine/codeception

            - wpengine/build_deploy:
                name:         deploy-development
                environment:  development
                requires:
                    - wpengine/lint
                    - wpengine/codeception
                filters:
                    branches:
                        only: development

            - wpengine/build_deploy:
                name:         deploy-staging
                environment:  staging
                requires:
                    - wpengine/lint
                    - wpengine/codeception
                filters:
                    branches:
                        only: staging

            - wpengine/build_deploy:
                name:         deploy-production
                environment:  production
                requires:
                    - wpengine/lint
                    - wpengine/codeception
                filters:
                    branches:
                        only:
                            - master
                            - production

    regression:
        jobs:
            - wpengine/backstop:
                config: tests/_backstop/index.js
                filters:
                    branches:
                        only:
                            - staging
