name: Lint files

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Identify lint commands
      id: commands
      run: |
        if [[ -f composer.json && $(composer run --list | grep "\blint\b") ]]; then c=true; else c=false; fi
        if [[ -f package.json && $(yarn run --non-interactive | grep "\blint\b") ]]; then p=true; else p=false; fi
        echo ::set-output name=composer::$c
        echo ::set-output name=package::$p

    - name: Run composer lint
      if: steps.commands.outputs.composer
      run: |
        composer validate
        composer install --prefer-dist --no-progress --no-suggest
        composer run-script lint

    - name: Run package lint
      if: steps.commands.outputs.package
      run: |
        yarn install --emoji false --no-progress --non-interactive
        yarn run lint
