name: PHP Composer

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Run composer lint
      run: 
        composer validate
        composer install --prefer-dist --no-progress --no-suggest
        composer run-script lint
      if: -f composer.json && $(composer run --list | grep "\blint\b")

    - name: Run package lint
      run: 
        yarn install --emoji false --no-progress --non-interactive
        yarn run lint
      if: -f package.json && $(yarn run | grep "\blint\b")
