name: Create Deploy PR

on:
  push:
    branches:
    - development
    - staging

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Create pull request
      uses: ./.github/actions/pull-request
      with:
        pr_assignee: ${{ github.actor }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
